services:
    app:
        image: tic-tac-toe-client
        container_name: tic-tac-toe-client
        build: .
        ports:
            - "3001:80"
        restart: unless-stopped
    
    server:
        image: tic-tac-toe-server
        container_name: tic-tac-toe-server
        build: 
            context: .
            dockerfile: Dockerfile.server
        ports:
            - "3002:3002"
        restart: unless-stopped
